"""empty message

Revision ID: 883cfa12f597
Revises: 8c937ea13960
Create Date: 2025-05-01 17:34:04.104436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883cfa12f597'
down_revision = '8c937ea13960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
